version: "3.7"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql

  php:
    build:
      context: ../docker-images/drupal
    container_name: ${PROJECT_NAME}_php
    environment:   
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - drupal:/var/www/html

  nginx:
    build:
      context: ../docker-images/nginx
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    volumes:
      - drupal:/var/www/html

  varnish:
    image: wodby/varnish:$VARNISH_TAG
    container_name: "${PROJECT_NAME}_varnish"
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
      VARNISH_CONFIG_PRESET: drupal
      VARNISH_ALLOW_UNRESTRICTED_PURGE: 1

  memcached:
    container_name: ${PROJECT_NAME}_memcached
    image: wodby/memcached:$MEMCACHED_TAG

  haproxy:
    build:
      context: ../docker-images/haproxy
      #args:
      #  - DOMAIN=${PROJECT_BASE_DOMAIN}
    container_name: ${PROJECT_NAME}_haproxy
    depends_on:
      - varnish
    ports:
      - 80:80
      - 443:443
      - 1936:1936

volumes:
  drupal:
  mariadb: